### ISSUE TITLE
Not using serverless profile

### ISSUE THREAD

**Issue by jwatts21** [deepakandgupta/serverless-dynamodb-stream-arn-plugin#2]
Hello,
I discovered that the plugin is using my AWS default profile instead of the profile configured in my serverless.yml. Is this intended behavior? I modified the index.js and added the following for my workaround:

```
let sprofile = this.serverless.service.provider.profile
AWS.config.credentials = new AWS.SharedIniFileCredentials({ profile: sprofile});

const data = await getDynamoDBStreams(
							region,
							tableName
						);

```

**Comment by deepakandgupta** [comment]
Hey,
Although I intended to use the default profile, you are right the plugin should use other profiles if provided.
Let me know if you are adding an MR. Otherwise, I'll add this in the next update.

**Comment by odoofrdadmin** [comment]
You can use 
set AWS_PROFILE=<profile> before to execute sls deploy

**Comment by deepakandgupta** [comment]
Closing this issue since I do not  think others had this use case and it has been a long time since I checked it
